name: Publish Packages
on: [workflow_dispatch]



      
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish
      run: dotnet nuget push "bin/Release/JBanning.AzureHelper.Queues.0.1.0.nupkg" --api-key GH_API_KEY --source "github"
